/**
 * PayGuard Domain Constants & Enums
 * Centralized dictionary of domain types, lifecycles, and operational statuses.
 */

const USER_ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  MERCHANT: 'MERCHANT',
  SUPPORT: 'SUPPORT',
});

const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
});

const MERCHANT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
});

const PAYMENT_GATEWAYS = Object.freeze({
  STRIPE: 'STRIPE',
  RAZORPAY: 'RAZORPAY',
  PAYPAL: 'PAYPAL',
  ADYEN: 'ADYEN',
  CHECKOUT: 'CHECKOUT',
  SIMULATED: 'SIMULATED',
});

const WEBHOOK_STATUS = Object.freeze({
  RECEIVED: 'RECEIVED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  REVERSED: 'REVERSED',
});

const FAILURE_SOURCES = Object.freeze({
  RULE_BASED: 'RULE_BASED',
  ML: 'ML',
  MANUAL: 'MANUAL',
});

const FAILURE_CATEGORIES = Object.freeze({
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  CARD_EXPIRED: 'CARD_EXPIRED',
  FRAUD_SUSPECTED: 'FRAUD_SUSPECTED',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  INVALID_DETAILS: 'INVALID_DETAILS',
  GATEWAY_ERROR: 'GATEWAY_ERROR',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  OTHERS: 'OTHERS',
});

const QUEUE_JOB_TYPES = Object.freeze({
  CLASSIFICATION: 'CLASSIFICATION',
  ANALYTICS: 'ANALYTICS',
  NOTIFICATION: 'NOTIFICATION',
});

const QUEUE_JOB_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
});

const AUDIT_ACTIONS = Object.freeze({
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_PASSWORD_CHANGE: 'USER_PASSWORD_CHANGE',
  USER_LOCK: 'USER_LOCK',
  MERCHANT_CREATE: 'MERCHANT_CREATE',
  MERCHANT_UPDATE: 'MERCHANT_UPDATE',
  MERCHANT_CONFIG_UPDATE: 'MERCHANT_CONFIG_UPDATE',
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  WEBHOOK_RETRY: 'WEBHOOK_RETRY',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_STATUS_UPDATE: 'PAYMENT_STATUS_UPDATE',
  PAYMENT_REVERSED: 'PAYMENT_REVERSED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  FAILURE_CLASSIFIED: 'FAILURE_CLASSIFIED',
  FAILURE_OVERRIDDEN: 'FAILURE_OVERRIDDEN',
  REPORT_REQUESTED: 'REPORT_REQUESTED',
  REPORT_GENERATED: 'REPORT_GENERATED',
  REPORT_DOWNLOADED: 'REPORT_DOWNLOADED',
  SYSTEM_SETTING_UPDATE: 'SYSTEM_SETTING_UPDATE',
});

const AUDIT_ACTOR_ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  MERCHANT: 'MERCHANT',
  SUPPORT: 'SUPPORT',
  SYSTEM: 'SYSTEM',
});

const REPORT_TYPES = Object.freeze({
  TRANSACTION_SUMMARY: 'TRANSACTION_SUMMARY',
  FAILURE_ANALYSIS: 'FAILURE_ANALYSIS',
  MERCHANT_RECONCILIATION: 'MERCHANT_RECONCILIATION',
  GATEWAY_PERFORMANCE: 'GATEWAY_PERFORMANCE',
  AUDIT_TRAIL: 'AUDIT_TRAIL',
});

const REPORT_FORMATS = Object.freeze({
  CSV: 'CSV',
  XLSX: 'XLSX',
  PDF: 'PDF',
});

const REPORT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED',
});

const STORAGE_TYPES = Object.freeze({
  LOCAL: 'LOCAL',
  S3: 'S3',
  GCS: 'GCS',
  AZURE_BLOB: 'AZURE_BLOB',
});

module.exports = {
  USER_ROLES,
  USER_STATUS,
  MERCHANT_STATUS,
  PAYMENT_GATEWAYS,
  WEBHOOK_STATUS,
  PAYMENT_STATUS,
  FAILURE_SOURCES,
  FAILURE_CATEGORIES,
  QUEUE_JOB_TYPES,
  QUEUE_JOB_STATUS,
  AUDIT_ACTIONS,
  AUDIT_ACTOR_ROLES,
  REPORT_TYPES,
  REPORT_FORMATS,
  REPORT_STATUS,
  STORAGE_TYPES,
};
